In [20]:
import numpy as np

a = np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

# ndarray属性示例

In [23]:
a.ndim

2

In [24]:
a.shape

(3, 5)

In [25]:
a.size

15

In [26]:
a.dtype

dtype('int32')

In [27]:
a.itemsize

4

In [28]:
a.data

In [29]:
a[0]

array([0, 1, 2, 3, 4])

In [30]:
a[0].ndim

1

In [34]:
a[:2]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [35]:
a[:3]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [36]:
a[:2].ndim

2

In [37]:
a[:3].ndim

2

## ndarray创建方式

In [39]:
b = np.array([1,2,3,4])
c = np.array(
 [
     [[1,2],[3,4]],
     [[5,6],[7,8]]
 ]
)

In [40]:
c.ndim

3

In [41]:
c.size

8

In [42]:
c.shape

(2, 2, 2)

In [43]:
## 使用tuple的方式
d = np.array(
 [
     ((1,2),(3,4)),
     ((5,6),(7,8))
 ]
)
d

In [45]:
d.shape

(2, 2, 2)

In [46]:
d.ndim

3

In [48]:
## 创建的时候制定dtype
e = np.array([(1,2),(3,4)], dtype=complex)
e

array([[ 1.+0.j,  2.+0.j],
       [ 3.+0.j,  4.+0.j]])

In [49]:
## 使用函数zeros, ones, empty(随机数) 生成
f1 = np.zeros( (1,2,3) )
f1

array([[[ 0.,  0.,  0.],
        [ 0.,  0.,  0.]]])

In [50]:
f2 = np.ones( (2,4) )
f2

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [52]:
f3 = np.empty( (3,3) )
f3

array([[  7.01573217e-322,   4.18967668e-321,   2.47032823e-323],
       [  2.61879535e-316,   0.00000000e+000,   3.23815565e-319],
       [  2.61894871e-316,   0.00000000e+000,   2.47032823e-323]])

In [55]:
## 其他函数
t1 = np.arange(1,7)
t1

array([1, 2, 3, 4, 5, 6])

In [56]:
t2 = np.linspace(2,8,6)
t2

array([ 2. ,  3.2,  4.4,  5.6,  6.8,  8. ])

In [57]:
## 其他函数
# array, zeros, zeros_like, ones, ones_like, empty, empty_like, arange, linspace, numpy.random.rand, numpy.random.randn, fromfunction, fromfile


## 基本运算

In [58]:
a = np.array([20,30,40,50])
b = np.arange(4)
b

array([0, 1, 2, 3])

In [59]:
c = a+b
c

array([20, 31, 42, 53])

In [60]:
b**2

array([0, 1, 4, 9], dtype=int32)

In [61]:
10*np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [62]:
a<35

array([ True,  True, False, False], dtype=bool)

In [63]:
a*b

array([  0,  30,  80, 150])

In [64]:
a.dot(b)

260

In [66]:
## 矩阵乘积
A=np.array([[2,1],
            [5,3]])
B=np.array([[10,2],
            [5,2]])
A.dot(B)

array([[25,  6],
       [65, 16]])

In [68]:
#某些操作（如+=何*=）可以修改现有数组，而不是创建新数组
A *= 3
A

array([[18,  9],
       [45, 27]])

In [69]:
B +=A
B

array([[28, 11],
       [50, 29]])

In [70]:
#类的方法操作，如a.sum,a.max,a.min
A.max()

45

In [71]:
A.sum()

99

In [72]:
A.min()

9

In [76]:
#类的操作还可以制定轴
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [77]:
a.sum(axis=0) ## sum of each coloum

array([12, 15, 18, 21])

In [78]:
a.min(axis=1) ## min of each row

array([0, 4, 8])

In [79]:
a.cumsum(axis=1)

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]], dtype=int32)

## 通用函数

In [81]:
np.sin(a)

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849, -0.54402111, -0.99999021]])

In [82]:
np.exp(a)

array([[  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
          2.00855369e+01],
       [  5.45981500e+01,   1.48413159e+02,   4.03428793e+02,
          1.09663316e+03],
       [  2.98095799e+03,   8.10308393e+03,   2.20264658e+04,
          5.98741417e+04]])

In [83]:
np.sqrt(a)

array([[ 0.        ,  1.        ,  1.41421356,  1.73205081],
       [ 2.        ,  2.23606798,  2.44948974,  2.64575131],
       [ 2.82842712,  3.        ,  3.16227766,  3.31662479]])

## 索引，切片，迭代

In [85]:
a[2]

array([ 8,  9, 10, 11])

In [86]:
a[:2]

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [87]:
a[2:5]

array([[ 8,  9, 10, 11]])

In [90]:
a=np.arange(10)**3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [91]:
a[:6]

array([  0,   1,   8,  27,  64, 125], dtype=int32)

In [92]:
a[:6:2]

array([ 0,  8, 64], dtype=int32)

In [93]:
a[:6:2]=-1   # equivalent to a[0:6:2] = -1; from start to position 6, exclusive, set every 2nd element to -1
a

array([ -1,   1,  -1,  27,  -1, 125, 216, 343, 512, 729], dtype=int32)

In [95]:
for i in a:
    print(i)

-1
1
-1
27
-1
125
216
343
512
729


In [108]:
b=np.arange(20).reshape(4,5)
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [109]:
b[0:4,2]

array([ 2,  7, 12, 17])

In [110]:
for i in b:
    print(i)

[0 1 2 3 4]
[5 6 7 8 9]
[10 11 12 13 14]
[15 16 17 18 19]


In [111]:
for i in b.flat:
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


## 改变数组形状

In [112]:
b.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [113]:
b.T

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

In [114]:
np.transpose(b)

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

In [115]:
b.resize(4,5)
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [116]:
#合并与分割

In [118]:
a = np.floor(10*np.random.random((2,2)))
a

array([[ 7.,  5.],
       [ 4.,  9.]])

In [119]:
b = np.floor(10*np.random.random((2,2)))
b

array([[ 3.,  4.],
       [ 0.,  9.]])

In [120]:
np.vstack((a,b))

array([[ 7.,  5.],
       [ 4.,  9.],
       [ 3.,  4.],
       [ 0.,  9.]])

In [121]:
np.hstack((a,b))

array([[ 7.,  5.,  3.,  4.],
       [ 4.,  9.,  0.,  9.]])

In [123]:
a = np.array([4.,2.])
b = np.array([3.,8.])
c=np.column_stack((a,b)) 
c

array([[ 4.,  3.],
       [ 2.,  8.]])

In [128]:
np.hsplit(c,2)

[array([[ 4.],
        [ 2.]]), array([[ 3.],
        [ 8.]])]

In [129]:
np.vsplit(c,2)

[array([[ 4.,  3.]]), array([[ 2.,  8.]])]

## 深度copy和浅copy

In [131]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [132]:
b=a
b is a

True

In [133]:
b.shape = 3,4
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [134]:
def f(x):
    print(id(x))
id(a)

171584128

In [135]:
f(a)

171584128


In [136]:
# 视图, 共享数据
c = a.view()
c is a

False

In [137]:
c.base is a

True

In [141]:
c.shape = 4,3
a.shape

(3, 4)

In [144]:
c[0,2] = 100
a

array([[  0,   1, 100,   3],
       [  4,   5,   6,   7],
       [  8,   9,  10,  11]])